name: Pre-commit Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    name: Pre-commit Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Validate commit messages
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      
      - name: Check code formatting
        run: npm run format:check
      
      - name: Run pre-commit hooks
        run: npm run pre-commit
      
      - name: Security audit
        run: npm audit --audit-level=high
      
      - name: Check for console.log statements
        run: |
          if grep -r "console\.\(log\|error\|warn\)" src/ --exclude-dir=__tests__ --exclude-dir=node_modules; then
            echo "Found console statements in production code!"
            exit 1
          fi